typedef unsigned char   undefined;

typedef unsigned long long    GUID;
typedef pointer32 ImageBaseOffset32;

typedef unsigned char    bool;
typedef unsigned char    byte;
typedef unsigned int    dword;
typedef long long    longlong;
typedef unsigned char    uchar;
typedef unsigned int    uint;
typedef unsigned long    ulong;
typedef unsigned long long    ulonglong;
typedef unsigned char    undefined1;
typedef unsigned short    undefined2;
typedef unsigned int    undefined4;
typedef unsigned long long    undefined6;
typedef unsigned long long    undefined8;
typedef unsigned short    ushort;
typedef unsigned short    wchar16;
typedef short    wchar_t;
typedef unsigned short    word;
typedef struct eCEntityAdmin eCEntityAdmin, *PeCEntityAdmin;

typedef struct vftable_eCEntityAdmin vftable_eCEntityAdmin, *Pvftable_eCEntityAdmin;

typedef struct bCSphere bCSphere, *PbCSphere;

typedef struct bCVector bCVector, *PbCVector;

typedef struct eCEntity eCEntity, *PeCEntity;

typedef struct eSEntityStatistics eSEntityStatistics, *PeSEntityStatistics;

typedef struct vftable_eCEntity vftable_eCEntity, *Pvftable_eCEntity;

typedef struct bCMatrix bCMatrix, *PbCMatrix;

typedef struct bCBox bCBox, *PbCBox;

typedef struct bCString bCString, *PbCString;

typedef struct bCVector4 bCVector4, *PbCVector4;

struct vftable_eCEntity {
    pointer GetVersion;
    pointer IsValid;
    pointer Write;
    pointer bCObjectBase_Write;
    pointer Read;
    pointer Destroy;
    pointer Create;
    pointer CopyFrom;
    pointer bCObjectRefBase_AddReference;
    pointer bCObjectRefBase_ReleaseReference;
    pointer bCObjectBase_GetReferenceCount;
    pointer bCObjectBase_GetProfileLastTicks1;
    pointer bCObjectBase_GetProfileLastTicks2;
    pointer bCObjectBase_GetProfileLastTicks3;
    pointer thunk_fun_304bc550;
    pointer bCObjectRefBase_IsVirtualRef;
    pointer bCObjectRefBase_PostInitialize;
    pointer bCObjectRefBase_NotifyProperty;
    pointer bCObjectRefBase_NotifyProperty2;
    pointer bCObjectRefBase_OnNotifyProperty1;
    pointer bCObjectRefBase_OnNotifyProperty2;
    pointer bCObjectRefBase_NotifyPropertyChange1;
    pointer bCObjectRefBase_NotifyPropertyChange2;
    pointer bCObjectRefBase_NotifyPropertyChange3;
    pointer GetParent;
    pointer GetParent2;
    pointer GetRoot;
    pointer GetChildAt;
    pointer GetChildAt2;
    pointer eCNode_SetContext;
    pointer eCNode_OnReadContent;
    pointer eCNode_AttachChild;
    pointer eCNode_AttachChildByIndex;
    pointer RemoveAllChildren;
    pointer eCNode_DoClone;
    pointer ChildrenAreAvailable;
    pointer SetName;
    pointer IsHelperParent;
    pointer IsResource;
    pointer IsResourceData;
    pointer IsKilled;
    pointer GetLinearVelocity;
    pointer GetLinearVelocity2;
    pointer IsDummy;
    pointer ReadV83;
    pointer ReadV63;
    pointer OnUpdatedWorldMatrix;
    pointer OnUpdatedWorldTreeBoundary;
    pointer SetWorldTreeBoundary;
    pointer SetLocalNodeBoundary;
    pointer SetWorldNodeBoundary;
    pointer SetLocalMatrix;
    pointer SetWorldPosition;
    pointer SetLocalPosition;
    pointer UpdateLocalBoundary;
    pointer UpdateParentDependencies;
    pointer UpdateChildDependencies;
    pointer AddPropertySet;
    pointer RemovePropertySet;
    pointer GetPropertySet;
    pointer Kill;
    pointer Decay;
    pointer IsAutoKillEnabled;
    pointer CreateFromTemplate;
    pointer OnCreateFromTemplate;
    pointer OnPatchWithTemplate;
    pointer SetCreator;
    pointer GetCreator;
    pointer HasCreator;
    pointer CopyEntityPrivateData;
    pointer Modified;
    pointer OnAction;
    pointer OnMouse;
    pointer OnEnterProcessingRange;
    pointer OnExitProcessingRange;
    pointer OnUpdateInternals;
    pointer OnProcess;
    pointer OnPreProcess;
    pointer OnPostProcess;
    pointer OnDeinitialize;
    pointer OnPostRead;
    pointer OnCacheIn;
    pointer OnCacheOut;
    pointer OnChildrenAvailable;
    pointer Trigger;
    pointer Render;
    pointer RenderAlpha;
};

struct bCVector4 { /* PlaceHolder Structure */
    float x;
    float y;
    float z;
    float w;
};

struct bCMatrix { /* PlaceHolder Structure */
    struct bCVector4 xAxis;
    struct bCVector4 yAxis;
    struct bCVector4 zAxis;
    struct bCVector4 extraAxis;
};

struct bCVector { /* PlaceHolder Structure */
    float x;
    float y;
    float z;

};

struct eSEntityStatistics { /* PlaceHolder Structure */
};

struct vftable_eCEntityAdmin {
    pointer GetVersion;
    pointer bCObjectBase_IsValid;
    pointer bCObjectBase_Write;
    pointer bCObjectBase_Write2;
    pointer bCObjectBase_Read;
    pointer Destroy;
    pointer Create;
    pointer CopyFrom;
    pointer bCObjectBase_AddReference;
    pointer bCObjectBase_ReleaseReference;
    pointer bCObjectBase_GetReferenceCount;
    pointer GetProfileLastTicksFirst;
    pointer bCObjectBase_GetProfileLastTicksFirst;
    pointer bCObjectBase_GetProfileLastTicks2;
    pointer thunk_FUN_304ca5d0;
    pointer field15_0x3c;
    pointer field16_0x40;
    pointer field17_0x44;
    pointer field18_0x48;
    pointer field19_0x4c;
    pointer field20_0x50;
    pointer field21_0x54;
    pointer field22_0x58;
    pointer field23_0x5c;
    pointer field24_0x60;
    pointer field25_0x64;
    pointer field26_0x68;
    pointer field27_0x6c;
    pointer field28_0x70;
    pointer field29_0x74;
    pointer field30_0x78;
    pointer field31_0x7c;
    pointer field32_0x80;
    pointer field33_0x84;
    pointer field34_0x88;
    pointer field35_0x8c;
    pointer field36_0x90;
    pointer field37_0x94;
    pointer field38_0x98;
    pointer field39_0x9c;
    pointer field40_0xa0;
    pointer field41_0xa4;
    pointer field42_0xa8;
    pointer field43_0xac;
    pointer field44_0xb0;
    pointer field45_0xb4;
    pointer field46_0xb8;
    pointer field47_0xbc;
    pointer field48_0xc0;
    pointer field49_0xc4;
    pointer field50_0xc8;
};

struct bCBox { /* PlaceHolder Structure */
    float min_x;
    float min_y;
    float min_z;
    float max_x;
    float max_y;
    float max_z;
};

struct bCSphere { /* PlaceHolder Structure */
    float radius;
    struct bCVector position;
};

struct bCString { /* PlaceHolder Structure */
    pointer data;
};

struct eCEntity { /* PlaceHolder Structure */
    struct vftable_eCEntity * vtable;
    undefined field1_0x4;
    undefined field2_0x5;
    undefined field3_0x6;
    undefined field4_0x7;
    undefined field5_0x8;
    undefined field6_0x9;
    undefined field7_0xa;
    undefined field8_0xb;
    undefined field9_0xc;
    undefined field10_0xd;
    undefined field11_0xe;
    undefined field12_0xf;
    undefined field13_0x10;
    undefined field14_0x11;
    ushort ProbablySomeArrayLength;
    struct eCEntity * ProbablySomeEntityChildArray;
    undefined field17_0x18;
    undefined field18_0x19;
    undefined field19_0x1a;
    undefined field20_0x1b;
    undefined field21_0x1c;
    undefined field22_0x1d;
    undefined field23_0x1e;
    undefined field24_0x1f;
    undefined field25_0x20;
    undefined field26_0x21;
    undefined field27_0x22;
    undefined field28_0x23;
    undefined field29_0x24;
    undefined field30_0x25;
    undefined field31_0x26;
    undefined field32_0x27;
    undefined field33_0x28;
    undefined field34_0x29;
    undefined field35_0x2a;
    undefined field36_0x2b;
    undefined field37_0x2c;
    undefined field38_0x2d;
    undefined field39_0x2e;
    undefined field40_0x2f;
    undefined4 some_field5;
    float renderAlphaValue;
    undefined field43_0x38;
    undefined field44_0x39;
    undefined field45_0x3a;
    undefined field46_0x3b;
    uint ManyFlags;
    struct bCMatrix WorldMatrix;
    struct bCMatrix some_matrix2;
    struct bCBox WorldTreeBoundary;
    struct bCSphere WorldTreeSphere;
    struct bCBox WorldNodeBoundary;
    struct bCSphere WorldNodeSphere;
    struct bCBox some_box5;
    float VisualLoDFactor;
    undefined4 some_field6;
    ulong DataChangedTimeStamp;
    float UniformScaling;
    struct bCString some_string;
    undefined field60_0x13c;
    undefined field61_0x13d;
    undefined field62_0x13e;
    undefined field63_0x13f;
    undefined field64_0x140;
    undefined field65_0x141;
    undefined field66_0x142;
    undefined field67_0x143;
    undefined field68_0x144;
    undefined field69_0x145;
    undefined field70_0x146;
    undefined field71_0x147;
    undefined field72_0x148;
    undefined field73_0x149;
    undefined field74_0x14a;
    undefined field75_0x14b;
    undefined field76_0x14c;
    undefined field77_0x14d;
    undefined field78_0x14e;
    undefined field79_0x14f;
    undefined field80_0x150;
    undefined field81_0x151;
    undefined field82_0x152;
    undefined field83_0x153;
    undefined field84_0x154;
    undefined field85_0x155;
    undefined field86_0x156;
    undefined field87_0x157;
    undefined field88_0x158;
    undefined field89_0x159;
    undefined field90_0x15a;
    undefined field91_0x15b;
    undefined field92_0x15c;
    undefined field93_0x15d;
    undefined field94_0x15e;
    undefined field95_0x15f;
    undefined field96_0x160;
    undefined field97_0x161;
    undefined field98_0x162;
    undefined field99_0x163;
    undefined field100_0x164;
    undefined field101_0x165;
    undefined field102_0x166;
    undefined field103_0x167;
    undefined field104_0x168;
    undefined field105_0x169;
    undefined field106_0x16a;
    undefined field107_0x16b;
    undefined field108_0x16c;
    undefined field109_0x16d;
    undefined field110_0x16e;
    undefined field111_0x16f;
    undefined field112_0x170;
    undefined field113_0x171;
    undefined field114_0x172;
    undefined field115_0x173;
    undefined field116_0x174;
    undefined field117_0x175;
    undefined field118_0x176;
    undefined field119_0x177;
    undefined field120_0x178;
    undefined field121_0x179;
    undefined field122_0x17a;
    undefined field123_0x17b;
    undefined field124_0x17c;
    undefined field125_0x17d;
    undefined field126_0x17e;
    undefined field127_0x17f;
    undefined field128_0x180;
    undefined field129_0x181;
    undefined field130_0x182;
    undefined field131_0x183;
    undefined field132_0x184;
    undefined field133_0x185;
    undefined field134_0x186;
    undefined field135_0x187;
    undefined field136_0x188;
    undefined field137_0x189;
    undefined field138_0x18a;
    undefined field139_0x18b;
    undefined4 some_field8;
    undefined2 some_field9;
    undefined field142_0x192;
    undefined field143_0x193;
    undefined4 some_field1;
    undefined4 some_field2;
    undefined4 some_field3;
    undefined4 some_field4;
    undefined field148_0x1a4;
};

struct eCEntityAdmin { /* PlaceHolder Class Structure */
    struct vftable_eCEntityAdmin * vtable;
};

